mysite/contact/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^map', 'contact.views.map'),
    url(r'^mail', 'contact.views.mail'),
    url(r'^$', 'contact.views.main'),
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^clients/', include('clients.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^admin/', include('settings.urls')),
    url(r'^$', 'catalog.views.home'),
    url(r'', include('pages.urls')),
)

mysite/settings/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^settings/', 'settings.views.settings'),
    url(r'^contact/', 'settings.views.contacts'),
)

mysite/suit/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^settings/', 'suit.views.settings'),
)

mysite/contact/models.py
from django.db import models

# Create your models here.

mysite/orders/models.py
# coding=utf-8
from django.db import models
from catalog.models import Product


# Create your models here.
class Order(models.Model):
    name = models.CharField("Имя", max_length=200)
    phone = models.CharField("Телефон", max_length=200)
    email = models.CharField("E-mail", max_length=200, blank=True)
    product_id = models.ForeignKey(Product, verbose_name="Заказан")
    date = models.DateField("Дата заказа", auto_now=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __unicode__(self):
        return self.name

    def get_product(self):
        return '<a target=_blank href="/catalog/' + str(self.product_id.product_category.url) + '/' + str(self.product_id.id) + '/">' + str(self.product_id.title) + '</a>'

    get_product.allow_tags = True
    get_product.short_description = 'Заказ'

mysite/pages/models.py
# -*- coding: utf-8 -*-
from django.db import models
from tinymce.models import HTMLField
from django.core.urlresolvers import reverse
from redactor.fields import RedactorField


# Create your models here.
class Section(models.Model):
    title = models.CharField("Название", max_length=200)
    description = models.CharField("Описание", max_length=200)
    keyword = models.CharField("Ключевые слова", max_length=200)
    text = RedactorField(verbose_name="Текст")
    url = models.CharField("Url", max_length=200)

    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'

    def __unicode__(self):
        return self.title


# класс стриницы
class Page(models.Model):
    title = models.CharField("Название", max_length=200)
    description = models.CharField("Описание", max_length=200)
    keyword = models.CharField("Ключевые слова", max_length=200)
    section = models.ForeignKey(Section, blank=True, default="-1", help_text="Раздел", null=True)
    text = RedactorField(verbose_name="Текст")
    url = models.CharField("Url", max_length=200)

    class Meta:
        verbose_name = 'Страница'
        verbose_name_plural = 'Страницы'

    def __unicode__(self):
        return self.title

mysite/settings/models.py
# coding=utf-8
from django.db import models


# Create your models here.
class Settings(models.Model):
    title = models.CharField("Название сайта", max_length=200)
    description = models.TextField("Описание сайта", max_length=200)
    phone_home = models.CharField("Тел. в шапке", max_length=200)
    email = models.CharField("E-mail", max_length=200)
    contacts = models.TextField("Контакты", blank=True)
    odnoklassniki = models.CharField("Одноклассники", max_length=200, blank=True)
    twitter = models.CharField("Twitter", max_length=200, blank=True)
    facebook = models.CharField("Facebook", max_length=200, blank=True)
    vk = models.CharField("Вконтакте", max_length=200, blank=True)
    footer = models.TextField("Текст в футере", blank=True, default="qwe")
    footer_link = models.TextField("Код счётчиков в футере", blank=True)


class Contact(models.Model):
    text = models.TextField()
    map = models.TextField("Код карты", blank=True)

mysite/contact/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.http import Http404
from django.template import RequestContext
from django.core.context_processors import csrf
from settings.models import Contact


def map(request):
    return render_to_response("map.html")


def mail(request):
    args = {}
    errors = []
    form = {}
    if request.POST:

        form['name'] = request.POST.get('name')
        form['email'] = request.POST.get('email')
        form['message'] = request.POST.get('message')

        if not form['name']:
            errors.append(u'Заполните имя')
        if '@' not in form['email']:
            errors.append(u'Введите корректный e-mail')
        if not form['message']:
            errors.append(u'Введите сообщение')

        if not errors:
            return HttpResponse(u'Спасибо за ваше сообщение!')

    args.update(csrf(request))
    args['errors'] = errors
    args['form'] = form

    return render_to_response('mail_form.html', args)


def main(request):
    args = {}
    errors = []
    form = {}
    model = Contact.objects.get(id=1)
    if request.POST:
        form['name'] = request.POST.get('name')
        form['email'] = request.POST.get('email')
        form['message'] = request.POST.get('message')
        if not form['name']:
            errors.append(u'Заполните имя')
        if '@' not in form['email']:
            errors.append(u'Введите корректный e-mail')
        if not form['message']:
            errors.append(u'Введите сообщение')
        if not errors:
            return HttpResponse(u'Спасибо за ваше сообщение!')

    args.update(csrf(request))
    args['errors'] = errors
    args['form'] = form
    args['model'] = model

    return render_to_response('contact.html', args)

mysite/settings/views.py
# coding=utf-8
from django.shortcuts import render_to_response, redirect
from django.http import Http404
from django.template import RequestContext
from django.core.context_processors import csrf
from settings.models import Settings, Contact


def settings(request):
    if request.user.is_authenticated():
        model = Settings.objects.get(id=1)
        args = {}
        if request.POST:
            model.title = request.POST.get('title')
            model.email = request.POST.get('email')
            model.description = request.POST.get('description')
            model.phone_home = request.POST.get('phone')
            model.contacts = request.POST.get('contacts')
            model.odnoklassniki = request.POST.get('odnoklassniki')
            model.twitter = request.POST.get('twitter')
            model.facebook = request.POST.get('facebook')
            model.vk = request.POST.get('vk')
            model.footer = request.POST.get('footer')
            model.footer_link = request.POST.get('footer_link')
            model.save()
            args['message'] = "yes"
        args.update(csrf(request))
        args['model'] = model
        return render_to_response("set.html", args)
    else:
        return redirect('/admin/')


def contacts(request):
    if request.user.is_authenticated():
        model = Contact.objects.get(id=1)
        args = {}
        if request.POST:
            model.text = request.POST.get('text')
            model.map = request.POST.get('map')
            model.save()
            args['message'] = "yes"
        args.update(csrf(request))
        args['model'] = model
        return render_to_response("contacts.html", args)
    else:
        return redirect('/admin/')

mysite/settings/templates/admin_menu.html
{#{% load sitetree %}#}
{% load i18n suit_menu %}
{% load url from future %}

<div class="left-nav" id="left-nav">
  <ul>
    {% block menu_home %}
      {% url 'admin:index' as index_url %}
      <li{% if index_url == request.path %} class="active"{% endif %}>
        <a href="{{ index_url }}"><i class="icon-home"></i>{% trans 'Home' %}
        </a>
      </li>
    {% endblock %}

    <li>
        <a href="/admin/catalog/category/"><i class="icon-chevron-right"></i>Catalog</a>
        <ul>
             <li><a href="/admin/catalog/category/">Категории</a></li>
             <li><a href="/admin/catalog/product/">Продукты</a></li>
        </ul>
    </li>

    <li>
        <a href="/admin/clients/client/"><i class="icon-chevron-right"></i>Clients</a>
        <ul>
            <li><a href="/admin/clients/client/">Клиенты</a></li>
        </ul>
    </li>

    <li>
        <a href="/admin/orders/order/"><i class="icon-chevron-right"></i>Orders</a>
        <ul>
            <li><a href="/admin/orders/order/">Заказы</a></li>
        </ul>
    </li>

    <li>
        <a href="/admin/pages/section/"><i class="icon-chevron-right"></i>Pages</a>
        <ul>
            <li><a href="/admin/pages/section/">Разделы</a></li>
            <li><a href="/admin/pages/page/">Страницы</a></li>
        </ul>
    </li>

    <li>
        <a href="/admin/auth/group/"><i class="icon-lock"></i>Пользователи и группы</a>
        <ul>
            <li><a href="/admin/auth/group/">Группы</a></li>
            <li><a href="/admin/auth/user/">Пользователи</a></li>
        </ul>
    </li>

    <li>
        <a href="/admin/settings/"><i class="icon-lock"></i>Настройки</a>
    </li>
    <li>
        <a href="/admin/contact/"><i class="icon-lock"></i>Контакты</a>
    </li>
  </ul>
</div>

mysite/settings/templates/contacts.html
<!DOCTYPE html>
<html lang="ru-ru" >
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Изменить Страница | Django Suit</title>
  <link rel="stylesheet" type="text/css" href=""/>
  <link rel="stylesheet" type="text/css" href="/static/suit/bootstrap/css/bootstrap.min.css" media="all"/>
  <link rel="stylesheet" type="text/css" href="/static/suit/css/suit.css" media="all">
  
  

  
  <script type="text/javascript">window.__admin_media_prefix__ = "/static/admin/";</script>
  <script src="/static/suit/js/jquery-1.8.3.min.js"></script>
  <script type="text/javascript">var Suit = { $: $.noConflict() }; if (!$) $ = Suit.$; </script>
  <script src="/static/suit/bootstrap/js/bootstrap.min.js"></script>
  
  <style type="text/css">.required:after { content: '*'; margin: 0 0 0 5px; position: absolute; color: #ccc;}</style>
  
  
  
  <script type="text/javascript" src="/admin/jsi18n/"></script>

  <link href="/static/redactor/css/redactor.css" type="text/css" media="all" rel="stylesheet" />
<link href="/static/redactor/css/django_admin.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/redactor/jquery.redactor.init.js"></script>
<script type="text/javascript" src="/static/redactor/redactor.js"></script>
<script type="text/javascript" src="/static/redactor/langs/ru.js"></script>
<script type="text/javascript" src="/static/redactor/plugins/fontcolor.js"></script>
<script type="text/javascript" src="/static/redactor/plugins/fontsize.js"></script>
<script type="text/javascript" src="/static/redactor/plugins/fontfamily.js"></script>
<script type="text/javascript" src="/static/redactor/plugins/textdirection.js"></script>


  
    <meta name="robots" content="NONE,NOARCHIVE"/>
</head>


<body class="pages-page change-form">

<!-- Sticky footer wrap -->
<div id="wrap">

  <!-- Container -->
  
    <div id="container">

      
        
          <!-- Header -->
          <div id="header" class="header">
            <div id="branding">
              <a href="/admin/"><h1 id="site-name">Django Suit</h1></a>
            </div>

            
            <div class="header-content header-content-first">
              <div class="header-column icon">
                <i class="icon-time"></i>
              </div>
              <div class="header-column">
              </div>
            </div>
            

            
              <!--<div class="header-content">
                <div class="header-column icon">
                  <i class="icon-comment"></i>
                </div>
                <div class="header-column">
                  <a href="" class="grey"><b>2</b> new messages</a>
                </div>
              </div>-->
            

            
              <div id="user-tools">
                Добро пожаловать,
                <strong>
                  
                    admin</strong>.
                <span class="user-links">
                
                  
                  
                  <a href="/admin/password_change/">Изменить пароль</a>
                  <span class="separator">|</span>
                  <a href="/admin/logout/">Выйти</a>
                  </span>
                
              </div>
            
            
          </div>
        
        <!-- END Header -->
      


      <div class="suit-columns two-columns">

        
          <div id="suit-center" class="suit-column">

            
              
    <ul class="breadcrumb">
      <li>
        <a href="/admin/">Начало</a>
        <span class="divider">&raquo;</span>
      </li>
      <li class="active">
        Контакты
      </li>
    </ul>
  
            

            
              
            

            <!-- Content -->
            <div id="content" class="colM row-fluid">
              
              
                <h2 class="content-title">Контакты</h2>
              
              
  <div id="content-main" class="inner-two-columns">

    <form enctype="multipart/form-data" action="/admin/contact/" method="post"
          id="page_form" class="form-horizontal">

      <div class="inner-right-column">

        <div class="box save-box">

          
<div class="submit-row clearfix">
  <button type="submit" class="btn btn-high btn-info" name="_save">Сохранить</button>
</div>


        </div>

      </div>
      <div class="inner-center-column">
        {% csrf_token %}
        
          
        
        <div class="tab-content tab-content-main">
          
          

          
          


          
            
              
<fieldset class="module aligned first ">
  
    
      <div class="control-group form-row field-text ">
        
          <div><div class="control-label"><label class="required" for="id_text">Текст:</label></div><div class="controls">
              <textarea cols="40" id="id_text" name="text" rows="10">
                {{ model.text }}
              </textarea>
              <script type="text/javascript">
                    jQuery(document).ready(function(jQuery){
                        var $field = jQuery("#id_text");
                        options = {"lang": "ru", "fileUpload": "/redactor/upload/file/", "plugins": ["fontcolor", "fontsize", "fontfamily", "textdirection"], "imageUpload": "/redactor/upload/image/", "buttonSource": "true"};
                        options.imageUploadErrorCallback = function(json){
                            alert(json.error);
                        };
                        $field.redactor(options);
                    });
                 </script></div></div>
        

      </div>

  
    
      <div class="control-group form-row field-url ">
        
          <div><div class="control-label"><label class="required" for="id_url">Код карты:</label></div><div class="controls">
              <textarea style="width:686px" class="vTextField" name="map">{{ model.map }}</textarea>
          </div></div>
        

      </div>
    
  
</fieldset>



            
          

          

          
          


          
            
          

        </div>

        

        
        


        

        
        
<script type="text/javascript">
(function($) {
    var field;


    field = {
        id: '#id_url',
        dependency_ids: [],
        dependency_list: [],
        maxLength: 200
    };

    
    field['dependency_ids'].push('#id_title');
    field['dependency_list'].push('title');
    

    
    $('.empty-form .form-row .field-url, .empty-form.form-row .field-url').addClass('prepopulated_field');
    $(field.id).data('dependency_list', field['dependency_list'])
               .prepopulate(field['dependency_ids'], field.maxLength);

})(django.jQuery);
</script>


      </div>
    </form>
  </div>

              
            </div>
            <!-- END Content -->
          </div>
        


        
          
            <div id="suit-left" class="suit-column">
              
                
                  
                    <form class="form-search nav-quick-search" autocomplete="off" action="/admin/auth/user/" method="GET">
                      <input type="text" name="q" class="input-medium search-query" id="quick-search">
                      <i class="input-icon icon-search"></i>
                      <input type="submit" class="submit" value="">
                    </form>
                  
                
              

              



<div class="left-nav" id="left-nav">
  <ul>
    
      
      <li>
        <a href="/admin/"><i class="icon-home"></i>Начало
        </a>
      </li>
    

    
    
      
        
          <li>
            <a href="/admin/catalog/category/"><i class="icon-chevron-right"></i>Catalog
            </a>
            
              <ul>
                
                  <li>
                    <a href="/admin/catalog/category/">Категории</a></li>
                
                  <li>
                    <a href="/admin/catalog/product/">Продукты</a></li>
                
              </ul>
            
          </li>
        
      
        
          <li>
            <a href="/admin/clients/client/"><i class="icon-chevron-right"></i>Clients
            </a>
            
              <ul>
                
                  <li>
                    <a href="/admin/clients/client/">Клиенты</a></li>
                
              </ul>
            
          </li>
        
      
        
          <li>
            <a href="/admin/orders/order/"><i class="icon-chevron-right"></i>Orders
            </a>
            
              <ul>
                
                  <li>
                    <a href="/admin/orders/order/">Заказы</a></li>
                
              </ul>
            
          </li>
        
      
        
          <li>
              <a href="/admin/pages/section/"><i class="icon-chevron-right"></i>Pages</a>
              <ul>
                  <li><a href="/admin/pages/section/">Разделы</a></li>
                  <li><a href="/admin/pages/page/">Страницы</a></li>
              </ul>
          </li>
        
      
        
          <li>
            <a href="/admin/auth/group/"><i class="icon-lock"></i>Пользователи и группы
            </a>
            
              <ul>
                
                  <li>
                    <a href="/admin/auth/group/">Группы</a></li>
                
                  <li>
                    <a href="/admin/auth/user/">Пользователи</a></li>
                
              </ul>
            
          </li>
        
      
    
      <li>
         <a href="/admin/settings/"><i class="icon-lock"></i>Настройки</a>
      </li>
      <li>
         <a href="/admin/contact/"><i class="icon-lock"></i>Контакты</a>
      </li>
  </ul>
</div>


            </div>
          
        

      </div>
    </div>
  

  
  <!-- Sticky footer push -->
  <div id="push"></div>
  

</div>


  
  <div id="footer" class="footer">
    <div class="content">
      <div class="tools">
        
          <a href="http://djangosuit.com/support/" target="_blank" class="icon"><i class="icon-question-sign"></i>Support</a>
          <a href="http://djangosuit.com/pricing/" target="_blank" class="icon"><i class="icon-bookmark"></i>Licence</a>
          <a href="http://github.com/darklow/django-suit/issues" target="_blank" class="icon"><i class="icon-comment"></i>Report a bug</a>
        
      </div>

      <div class="copyright">
        
          Copyright &copy; 2013 DjangoSuit.com<br>Developed by <a href="http://djangosuit.com" target="_blank">DjangoSuit.com</a>
        
      </div>

      <div class="branding">
        
          Django Suit
          
            v0.2.11
          
        
      </div>
    </div>
  </div>
  


  <script src="/static/suit/js/suit.js"></script>
  
  

  
    <!-- Warn on leaving unsaved form -->
    <script src="/static/suit/js/suit-form-confirm.js"></script>
    <script type="text/javascript">
      confirmExitIfModified('page_form', 'You have unsaved changes.');
    </script>
  

  
        
  <script>
    (function ($) {
      $(function () {
        $("#page_form").suit_form_debounce();
      });
    }(Suit.$))    
  </script>

    <style>
      .form-row input {
          width: 685px;
      }
  </style>


</body>
</html>

mysite/settings/templates/settings.html
{% extends "main_admin.html" %}
{% load admin_menu %}
{% block content-center %}
  <div id="suit-center" class="suit-column">

      {% block breadcrumbs %}
        <ul class="breadcrumb">
          <li>
              <a href="/admin/">Начало</a>
              <span class="divider">&raquo;</span>
          </li>
          <li class="active"><a href="/admin/settings/">Настройки</a></li>
        </ul>
      {% endblock %}

    {% block messages %}
      {% if message == "yes" %}
        <div class="alert alert-success">
            <button class="close" data-dismiss="alert">×</button>
            Настройки успешно изменены.
         </div>
      {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="colM row-fluid">

        <div id="content-main" class="inner-two-columns">

            <form enctype="multipart/form-data" action="/admin/settings/" method="post" id="settings_form" class="form-horizontal">

                <div class="inner-right-column">

                    <div class="box save-box">
                        <div class="submit-row clearfix">
                            <button type="submit" class="btn btn-high btn-info" name="_save">Сохранить</button>
                        </div>
                    </div>
                    </div>

                <div class="inner-center-column">
                    {% csrf_token %}
                    <div class="tab-content tab-content-main">
                        <fieldset class="module aligned first ">
                            <div class="control-group form-row field-title ">
                                <div>
                                    <div class="control-label">
                                        <label class="required" for="id_title">Название сайта:</label>
                                    </div>
                                    <div class="controls">
                                        <input class="vTextField" id="id_title" maxlength="200" name="title" type="text" value="{{ model.title }}">
                                    </div>
                                </div>
                            </div>

                            <div class="control-group form-row field-description ">
                                <div>
                                    <div class="control-label">
                                        <label class="required" for="id_description">Описание:</label>
                                    </div>
                                    <div class="controls">
                                        <input class="vTextField" id="id_description" maxlength="200" name="description" type="text" value="{{ model.description }}">
                                    </div>
                                </div>
                            </div>

                            <div class="control-group form-row">
                                <div>
                                    <div class="control-label">
                                        <label class="required">Телефон (в шапке):</label>
                                    </div>
                                    <div class="controls">
                                        <input class="vTextField" id="id_phone" maxlength="200" name="phone" type="text" value="{{ model.phone_home }}">
                                    </div>
                                </div>
                            </div>

                            <div class="control-group form-row">
                                <div>
                                    <div class="control-label">
                                        <label class="required">E-mail:</label>
                                    </div>
                                    <div class="controls">
                                        <input class="vTextField" id="id_mail" maxlength="200" name="email" type="text" value="{{ model.email }}">
                                    </div>
                                </div>
                            </div>

                            <div class="control-group form-row">
                                <div>
                                    <div class="control-label">
                                        <label class="required">Контакты:</label>
                                    </div>
                                    <div class="controls">
                                        <input class="vTextField" id="id_contacts" maxlength="200" name="contacts" type="text" value="{{ model.contacts }}">
                                    </div>
                                </div>
                            </div>

                            <div class="control-group form-row">
                                <div>
                                    <div class="control-label">
                                        <label class="required">Одноклассники:</label>
                                    </div>
                                    <div class="controls">
                                        <input class="vTextField" id="id_odnoklassniki" maxlength="200" name="odnoklassniki" type="text" value="{{ model.odnoklassniki }}">
                                    </div>
                                </div>
                            </div>

                            <div class="control-group form-row">
                                <div>
                                    <div class="control-label">
                                        <label class="required">Twitter:</label>
                                    </div>
                                    <div class="controls">
                                        <input class="vTextField" id="id_twitter" maxlength="200" name="twitter" type="text" value="{{ model.twitter }}">
                                    </div>
                                </div>
                            </div>

                            <div class="control-group form-row">
                                <div>
                                    <div class="control-label">
                                        <label class="required">Facebook:</label>
                                    </div>
                                    <div class="controls">
                                        <input class="vTextField" id="id_facebook" maxlength="200" name="facebook" type="text" value="{{ model.facebook }}">
                                    </div>
                                </div>
                            </div>

                            <div class="control-group form-row">
                                <div>
                                    <div class="control-label">
                                        <label class="required">Вконтакте:</label>
                                    </div>
                                    <div class="controls">
                                        <input class="vTextField" id="id_vk" maxlength="200" name="vk" type="text" value="{{ model.vk }}">
                                    </div>
                                </div>
                            </div>

                            <div class="control-group form-row field-text ">

                                  <div><div class="control-label"><label class="required" for="id_text">Текст:</label></div><div class="controls">
                                      <textarea cols="40" id="id_text" name="text" rows="10">
                                        {{ model.text }}
                                      </textarea>
                                      <script type="text/javascript">
                                            jQuery(document).ready(function(jQuery){
                                                var $field = jQuery("#id_text");
                                                options = {"lang": "ru", "fileUpload": "/redactor/upload/file/", "plugins": ["fontcolor", "fontsize", "fontfamily", "textdirection"], "imageUpload": "/redactor/upload/image/", "buttonSource": "true"};
                                                options.imageUploadErrorCallback = function(json){
                                                    alert(json.error);
                                                };
                                                $field.redactor(options);
                                            });
                                         </script></div></div>


                              </div>

                        </fieldset>
                    </div>
                </div>

            </form>

        </div>
    </div>
    <!-- END Content -->
  </div>
  <style>
      #settings_form input[type="text"]{
        width: 500px;
      }
  </style>
{% endblock %}


{% block content-left %}
  {% if not is_popup %}
    <div id="suit-left" class="suit-column">
    <form class="form-search nav-quick-search" autocomplete="off" action="/admin/auth/user/" method="GET">
      <input type="text" name="q" class="input-medium search-query" id="quick-search">
      <i class="input-icon icon-search"></i>
      <input type="submit" class="submit" value="">
    </form>

     {% admin_menu %}

    </div>
  {% endif %}
{% endblock %}